image: rust:latest

stages:
  - build

rust:
  stage: build
  script:
    - curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v3.15.8/protoc-3.15.8-linux-x86_64.zip
    - unzip protoc-3.15.8-linux-x86_64.zip -d $HOME/.local
    - export PATH="$PATH:$HOME/.local/bin"
    - cargo build
